// flow-typed signature: b37e883d351f56fccf8e0349b6c3ae17
// flow-typed version: <<STUB>>/bourbon-neat_v^1.9.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bourbon-neat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bourbon-neat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bourbon-neat/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'bourbon-neat/Gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bourbon-neat/eyeglass-exports.js' {
  declare module.exports: $Exports<'bourbon-neat/eyeglass-exports'>;
}
declare module 'bourbon-neat/Gulpfile.js' {
  declare module.exports: $Exports<'bourbon-neat/Gulpfile'>;
}
declare module 'bourbon-neat/index' {
  declare module.exports: $Exports<'bourbon-neat'>;
}
declare module 'bourbon-neat/index.js' {
  declare module.exports: $Exports<'bourbon-neat'>;
}
