// flow-typed signature: 880e4c5f0a1d8020f4831c19ec54ca93
// flow-typed version: <<STUB>>/node-neat_v^2.0.0-beta.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-neat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-neat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-neat/test/with_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-neat/index' {
  declare module.exports: $Exports<'node-neat'>;
}
declare module 'node-neat/index.js' {
  declare module.exports: $Exports<'node-neat'>;
}
declare module 'node-neat/test/with_test.js' {
  declare module.exports: $Exports<'node-neat/test/with_test'>;
}
