// flow-typed signature: cd4eddbf5f532bb52fb583e0ea1021e6
// flow-typed version: <<STUB>>/node-bourbon_v^4.2.8/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-bourbon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-bourbon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-bourbon/test/path_test' {
  declare module.exports: any;
}

declare module 'node-bourbon/test/with_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-bourbon/index' {
  declare module.exports: $Exports<'node-bourbon'>;
}
declare module 'node-bourbon/index.js' {
  declare module.exports: $Exports<'node-bourbon'>;
}
declare module 'node-bourbon/test/path_test.js' {
  declare module.exports: $Exports<'node-bourbon/test/path_test'>;
}
declare module 'node-bourbon/test/with_test.js' {
  declare module.exports: $Exports<'node-bourbon/test/with_test'>;
}
